apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: db
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: db_prod
          volumeMounts:
            - name: sql-volume
              mountPath: /docker-entrypoint-initdb.d/script.sql
            - name: data-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: sql-volume
          persistentVolumeClaim:
            claimName: sql-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 

