apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./script.sql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
